name: Generate and Publish Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install DocFX
      run: dotnet tool install -g docfx
    
    - name: Build project
      run: |
        cd Calculator
        dotnet build --configuration Release
    
    - name: Build Documentation with docfx
      run: |
        cd Calculator
        docfx docfx.json
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Calculator/_site
        destination_dir: docs